# Generated by Django 2.1 on 2018-08-07 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='images/None/no-group-icon.jpg', upload_to='images/Elements/')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('creation_name', models.DateField(default=django.utils.timezone.now)),
                ('verified', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='images/None/no-element-icon.jpg', upload_to='images/Groups/')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_groups', to='groups.Group')),
            ],
        ),
        migrations.AddField(
            model_name='elements',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='groups.Group'),
        ),
    ]
