# Generated by Django 2.1 on 2018-08-07 10:22

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180807_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='icon',
            field=models.ImageField(default='Images/None/no-group-icon.jpg', upload_to='Images/Elements/', validators=[groups.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(default='Images/None/no-element-icon.jpg', upload_to='Images/Groups/', validators=[groups.validators.validate_image_extension]),
        ),
    ]
